### PR TITLE
chore: barcalendar Redwood updates

### PR DESCRIPTION
**Pull request by cmltaWt0**
Changes:
- removed Redwood from future releases
- changed CURRENT and EDX version of everything

@feanil I didn't change Mongo, MySQL, Elasticsearch, Redis, Ruby for EDX. I need an info about the current software versions for edx.org.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @cmltaWt0! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by feanil** [comment]
@robrap FYI, if you want to update the edx versions on the support windows spreadsheet, this is the place to do it.  @cmltaWt0 I think we can just merge this without those updates and I'll re-run the code on the spreadsheet to update.

**Review by feanil — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@cmltaWt0 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/repo-tools&entry.867055334=https://github.com/openedx/repo-tools/pull/529&entry.1484655318=https://github.com/cmltaWt0&entry.752974735=2024-06-25+11:32&entry.1917517419=2024-06-25+15:58&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by robrap** [comment]
Thanks @feanil. Was there a specific context for this inform, or just a very general inform?

**Comment by feanil** [comment]
Very general, this info is out of date and if you're relying on it, you may want to update, if you're no longer using this let me know and we can drop the data from the sheet.

**Comment by robrap** [comment]
@feanil: When you say:
> ... let me know and we can drop the data from the sheet
What are you referring to? Are you referring to specific data, or are you talking about the [entire Support Window spreadsheet](https://docs.google.com/spreadsheets/d/11DheEtMDGrbA9hsUvZ2SEd4Cc8CaC4mAfoV8SVaLBGI/edit?gid=195838733#gid=195838733)? The spreadsheet is certainly useful.

Related, that spreadsheet has an [IDA and Upgrade status](https://docs.google.com/spreadsheets/d/11DheEtMDGrbA9hsUvZ2SEd4Cc8CaC4mAfoV8SVaLBGI/edit?gid=1850889545#gid=1850889545) tab that seems quite out-of-date. How is that updated, and who uses this?

FYI: @jristau1984

**Comment by feanil** [comment]
So there is a 2U specific copy of this but also the public one under Axim control. There is also this script that updates the data with the latest info for 2U and for the community supported release.  I'm wondering if it is useful to still have the code in place that annotates the 2U specific states on the sheets.  If it is still useful, please update the state in the code so that it matches the current state of your systems.  If it is not useful and is going to become out of date, let me know and I'll just remove the 2U specific bits rather than have out of date information.

**Comment by robrap** [comment]
@feanil: Did you mean for "this script" to be a link?

**Comment by feanil** [comment]
No, it's the script that this PR is making updates to.

**Comment by robrap** [comment]
@feanil: Sorry if I am just dense.
> I'm wondering if it is useful to still have the code in place that annotates the 2U specific states on the sheets.
Can you link to code or provide more specifics of what this refers to, and what is 2U specific. I don't see any code comments about "2U". Thank you.

**Comment by feanil** [comment]
Hey Robert, in the above script it's the list for EDX  https://github.com/openedx/repo-tools/pull/529/files#diff-6e6d825c68b262c504907d44b64d49805aea642c3280b4a2a84b3459cb2d2664L418-L457

**Comment by robrap** [comment]
Thanks @feanil. I can determine whether this information is useful internally, but is it useful to the community at all as well while doing upgrades? Or would this information be updated too late for it to ever be useful, because those details would have come in through another mechanism?

**Pull request merged**
