### PR TITLE
fix: use default branch when openedx.org/release annotation is empty

### PR DESCRIPTION
**Pull request by cmltaWt0**
The bug is hard to detect.

The tool shows the correct count of repos to be cut but the result list lacks repos with `null` values in `openedx.org/release` annotation.
```
Find commits  : 100%|█████████████████████████| 45/45 [00:33<00:00,  1.36it/s]
```

Without the fix (41):
```
openedx/aspects-dbt
openedx/course-discovery
openedx/credentials
openedx/cs_comments_service
openedx/docs.openedx.org
openedx/ecommerce-worker
openedx/ecommerce
openedx/edx-documentation
openedx/edx-notes-api
openedx/edx-platform
openedx/enterprise-access
openedx/enterprise-catalog
openedx/enterprise-subsidy
openedx/event-bus-redis
openedx/frontend-app-account
openedx/frontend-app-authn
openedx/frontend-app-communications
openedx/frontend-app-course-authoring
openedx/frontend-app-discussions
openedx/frontend-app-ecommerce
openedx/frontend-app-gradebook
openedx/frontend-app-learner-dashboard
openedx/frontend-app-learner-record
openedx/frontend-app-learning
openedx/frontend-app-ora-grading
openedx/frontend-app-ora
openedx/frontend-app-payment
openedx/frontend-app-profile
openedx/frontend-app-publisher
openedx/frontend-app-support-tools
openedx/frontend-plugin-framework
openedx/license-manager
openedx/openedx-app-android
openedx/openedx-app-ios
openedx/openedx-demo-course
openedx/openedx-test-course
openedx/platform-plugin-aspects
openedx/testeng-ci
openedx/tutor-contrib-aspects
openedx/xblock-skill-tagging
openedx/xqueue
```

With fix (45):
```
openedx/aspects-dbt
openedx/axim-engineering
openedx/course-discovery
openedx/credentials
openedx/cs_comments_service
openedx/docs.openedx.org
openedx/ecommerce-worker
openedx/ecommerce
openedx/edx-documentation
openedx/edx-lint
openedx/edx-notes-api
openedx/edx-platform
openedx/enterprise-access
openedx/enterprise-catalog
openedx/enterprise-subsidy
openedx/event-bus-redis
openedx/frontend-app-account
openedx/frontend-app-authn
openedx/frontend-app-communications
openedx/frontend-app-course-authoring
openedx/frontend-app-discussions
openedx/frontend-app-ecommerce
openedx/frontend-app-gradebook
openedx/frontend-app-learner-dashboard
openedx/frontend-app-learner-record
openedx/frontend-app-learning
openedx/frontend-app-ora-grading
openedx/frontend-app-ora
openedx/frontend-app-payment
openedx/frontend-app-profile
openedx/frontend-app-publisher
openedx/frontend-app-support-tools
openedx/frontend-plugin-framework
openedx/frontend-template-application
openedx/license-manager
openedx/openedx-app-android
openedx/openedx-app-ios
openedx/openedx-demo-course
openedx/openedx-test-course
openedx/platform-plugin-aspects
openedx/repo-tools
openedx/testeng-ci
openedx/tutor-contrib-aspects
openedx/xblock-skill-tagging
openedx/xqueue
```

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @cmltaWt0! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by cmltaWt0** [comment]
@kdmccormick @feanil 
This is a proposed change to use default branch  when we have a `null` values in `openedx.org/release` annotation.

**Review by kdmccormick — CHANGES_REQUESTED** [review]
I would rather not treat "null" as "default branch"--I think that would be surprising behavior for people reading catalog-info.yml files. When I see "null", I think "not applicable".

If we do want new repos to be in the release, I think we should update frontend-template-app and edx-cookiecutters to use main/master.

Alternatively, we could just exclude new repos from the release until they explicitly opt-in by adding a branch to catalog-info.yml

**Comment by cmltaWt0** [comment]
Closing the PR as we decided that the current behaviour is desired.

**Comment by openedx-webhooks** [comment]
@cmltaWt0 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/repo-tools&entry.867055334=https://github.com/openedx/repo-tools/pull/511&entry.1484655318=https://github.com/cmltaWt0&entry.752974735=2024-05-08+16:43&entry.1917517419=2024-05-08+19:18&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
