### PR TITLE
Fix test cases after bot PR for updating python requirements

### PR DESCRIPTION
**Pull request by salman2013**

### CODE REVIEW

**Comment by feanil** [comment]
Is a longer term fix to update https://github.com/openedx/repo-tools/blob/master/Makefile#L39 to also upgrade the py312 files?

**Comment by salman2013** [comment]
@feanil I believe you are right but I was not sure about updating https://github.com/openedx/repo-tools/blob/master/Makefile#L39, there were some package version conflicts in extra-py312 file and i discussed with BOM team which created these files, they mentioned me to update the files locally with python 3.12 environment. 
What if we merge this for now and let me update the make file separately?

**Review by feanil — APPROVED** [review]
Sounds good to me, let me know when this is out of draft and I can merge it.

**Comment by salman2013** [comment]
@feanil PR is ready to merge.

**Review by feanil — APPROVED** [review]

**Pull request merged**
